# Generated by Django 3.1.7 on 2021-04-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_academy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academy',
            table='academys',
        ),
        migrations.AlterModelTable(
            name='formed',
            table='formeds',
        ),
    ]
