# Generated by Django 3.1.7 on 2021-04-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210422_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='subject6',
        ),
    ]
