# Generated by Django 3.1.7 on 2021-04-23 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_stu_info'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stu_info',
            table=None,
        ),
    ]
