# Generated by Django 3.1.7 on 2021-03-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210328_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plogin',
            old_name='Password',
            new_name='email',
        ),
    ]
