# Generated by Django 3.1.7 on 2021-05-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210514_1925'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academy',
            table=None,
        ),
    ]
