# Generated by Django 3.1.7 on 2021-05-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210514_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='certi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship', models.FileField(upload_to='')),
                ('course', models.FileField(upload_to='')),
            ],
        ),
    ]
