# Generated by Django 3.1.7 on 2021-03-27 13:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
