# Generated by Django 3.1.7 on 2021-04-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210328_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plogins',
            new_name='logged',
        ),
    ]
