# Generated by Django 3.1.7 on 2021-04-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210411_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logged',
            new_name='formed',
        ),
    ]
