# Generated by Django 3.1.7 on 2021-04-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210419_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField(max_length=10)),
                ('percentage', models.FloatField(max_length=10)),
                ('subject1', models.FloatField(max_length=10)),
                ('subject2', models.FloatField(max_length=10)),
                ('subject3', models.FloatField(max_length=10)),
                ('subject4', models.FloatField(max_length=10)),
                ('subject5', models.FloatField(max_length=10)),
                ('subject6', models.FloatField(max_length=10)),
                ('kt', models.FloatField(max_length=10)),
            ],
        ),
    ]
