# Generated by Django 3.1.7 on 2021-04-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210422_1202'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academy',
            table='academy',
        ),
        migrations.AlterModelTable(
            name='formed',
            table='formed',
        ),
    ]
