# Generated by Django 3.1.7 on 2021-04-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_academy_subject6'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.IntegerField(max_length=5)),
                ('roll', models.IntegerField(max_length=2)),
                ('department', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=10)),
                ('mother_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('sign', models.FileField(null=True, upload_to='')),
                ('dob', models.DateField()),
                ('student_email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='year')),
                ('address', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=10)),
                ('email_mother', models.EmailField(max_length=254)),
                ('email_father', models.EmailField(max_length=254)),
                ('number_father', models.IntegerField(max_length=10)),
                ('number_mother', models.IntegerField(max_length=10)),
                ('designation_mother', models.CharField(max_length=20)),
                ('designation_father', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Stu_infos',
            },
        ),
    ]
