# Generated by Django 3.1.7 on 2021-04-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210423_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_info',
            name='idNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stu_info',
            name='number_father',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stu_info',
            name='number_mother',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stu_info',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stu_info',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
