# Generated by Django 3.1.7 on 2021-05-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_student_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_add',
            name='email',
        ),
        migrations.AddField(
            model_name='student_add',
            name='idNumber',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
