# Generated by Django 3.1.7 on 2021-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210513_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='cgpa',
            field=models.FloatField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='kt',
            field=models.FloatField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='percentage',
            field=models.FloatField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='subject1',
            field=models.FloatField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='subject2',
            field=models.FloatField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='subject3',
            field=models.FloatField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='subject4',
            field=models.FloatField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='subject5',
            field=models.FloatField(max_length=70),
        ),
    ]
