# Generated by Django 3.1.7 on 2021-05-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210514_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stu_info',
            old_name='year',
            new_name='current_year',
        ),
    ]
