# Generated by Django 3.1.7 on 2021-05-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210521_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_info',
            name='completion_year',
            field=models.IntegerField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='academy',
            name='cgpa',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='kt',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='percentage',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='subject1',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='subject2',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='subject3',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='subject4',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='academy',
            name='subject5',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='stu_info',
            name='current_year',
            field=models.TextField(max_length=50),
        ),
    ]
