# Generated by Django 3.1.7 on 2021-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210521_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='certi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship', models.FileField(null=True, upload_to='')),
                ('course', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
