# Generated by Django 3.1.7 on 2021-05-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210521_2332'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certi',
            table='Certis',
        ),
    ]
